### ISSUE TITLE
[code_search] Distributed Training with T2T does not work

### ISSUE THREAD

**Issue by activatedgeek** [kubeflow/examples#208]
Distributed training for the Code Search example with T2T seems to hang at

```
INFO:tensorflow:Graph was finalized.
```

A similar issue has been reported at https://github.com/tensorflow/tensor2tensor/issues/926.

/area example/code_search

**Comment by Mack-y** [comment]
hello~ have you fixed it?

**Comment by activatedgeek** [comment]
Hey @Mack-y, unfortunately I have not looked into much detail here with T2T. If you are using vanilla TF, then the Kubeflow example should work right away. This seems to be a regression in Tensor2Tensor.

**Comment by cwbeitel** [comment]
@activatedgeek Ah ha since updating to the most recent version of t2t I now see this problem as well (with distributed training as well as non-distributed, which both worked previously [different model and problem]). Something to look into would be trying prior versions of t2t or tensorflow.

/cc @jlewi

**Comment by cwbeitel** [comment]
@activatedgeek Reverting to a previous version of t2t fixed the problem for me! I believe the version I'm using here is a few of my own non-core commits beyond 49e279eb6c871fbebc137d6f598758a275f521c3 which is circa Jun 15th but you may not need to go that far back.

/cc @jlewi

**Comment by lawdpls** [comment]
@activatedgeek @cwbeitel Have you guys tried the `continuous_train_and_evaluate` schedule? I tried that on a tiny toy cluster with async training and it worked.

The default schedule for distributed workers is `train` which invokes tf.estimator.Estimator.train, which in itself is not distributed-aware. `continuous_train_and_evaluate` on the other hand calls tf.estimator.train_and_evaluate, and the latter has the cluster config and related stuff handled in the wrapper.

**Comment by lawdpls** [comment]
@cwbeitel AFAIK `train` can still work, but you need to tweak the T2T code. I tried the workaround mentioned in [issue #926](https://github.com/tensorflow/tensor2tensor/issues/926), basically creating `tf.train.clusterspec` in `utils/trainer_lib.py` for all workers using any schedules(`train` included). My take on this is that the T2T devs overlooked the fact that train() and train_and_evaluate() are not APIs of the same level so they forgot to instantiate clusterspec for train().

In the test runs I used `train` only on resnet + cifar with modified T2T. Somehow I got a few `NaN` loss errors but most of the time it worked normally.

**Comment by cwbeitel** [comment]
Thanks @lawdpls for your insights. Maybe you or @jinliangwei could send a PR to t2t with the changes?

**Comment by jlewi** [comment]
Per @cwbeitel's comment I tried; tensor2tensor49e279eb6c871fbebc137d6f598758a275f521c3 

Same problem gets stuck at;

```
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
```

I tried patching the fix tensorflow/tensor2tensor#926 code is on this branch:
https://github.com/jlewi/tensor2tensor/tree/fix_dist_train

That ended up giving me the error

```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/notebooks/src/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/notebooks/src/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/notebooks/src/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 385, in main
    save_metadata(hparams)
  File "/notebooks/src/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 337, in save_metadata
    new_hparams.del_hparam("modality")
AttributeError: 'HParams' object has no attribute 'del_hparam'
```

**Comment by jlewi** [comment]
Looks like HParams is defined in TF; so maybe its because I'm using a version of TF that is too old; I'm using 1.8 right now.

**Comment by cwbeitel** [comment]
@jlewi Maybe try a commit or two before that one? If all else fails the version of t2t I'm currently using is in NFS in kubeflow-rl at /mnt/nfs-east1-d/work/tk/vendor/tensor2tensor. You could diff it against that commit but I thought that was the one I was using.

**Comment by cwbeitel** [comment]
Looks like my training workers are installing that version of t2t on top of tensorflow/tensorflow:latest-gpu so yeah I'd try the most recent tf.

**Comment by jlewi** [comment]
So after doing the following 
  1. Upgrading to TF 1.11
  1. Patching in the fix to #926

I get past finalized graph but now I get stuck at

```
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized:
```
I think this indicates none of the workers are registered as the chief.

I think this line might be the problem
https://github.com/tensorflow/tensorflow/blob/5990afceae207e395139e702979fcf9176518cf9/tensorflow/contrib/learn/python/learn/estimators/run_config.py#L159

It looks like T2T is still using the old contrib estimator; and this will not use worker 0 as the chief if the envronment is set to cloud; which it is.

**Comment by jlewi** [comment]
From @cwbeitel  https://github.com/kubeflow/examples/issues/314#issuecomment-436500220

> Distributed training is working for me with a function that runs on startup to parse the TF_CONFIG into the appropriate FLAGS, see https://github.com/cwbeitel/tk/blob/master/tk/experiment.py#L389

It looks like @cwbeitel is doing synchronous training as opposed to async training.

Looking at the [docs](https://github.com/tensorflow/tensor2tensor/blob/master/docs/distributed_training.md)

* In async mode there is a chief replica but the corresponding "--worker_id" flag is 0; and the "worker_id" flag for the first "worker" is "1"
  * I suspect this is because TF estimator relies on the chief replica in TF_CONFIG to determine that
    the process is a chief while; the T2T code is relying on worker_id

* in sync mode workers run schedule "run_std_server"

I'm going to try sync mode just because it seems simpler to configure.

**Comment by jlewi** [comment]
With sync training and using T2T 1.10. I hit the ps  (which are really the workers) are just supposed to call run_std_server. They are crashing with the following exception.

```
"Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 354, in main
    run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 346, in run_std_server
    exp.run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 496, in run_std_server
    protocol=self._hparams.std_server_protocol)
AttributeError: 'NoneType' object has no attribute 'std_server_protocol'
```

This looks like a bug in the code to me.

Here's where the code is constructing the T2T experiment and invoking run_std_server
https://github.com/tensorflow/tensor2tensor/blob/091373cd5eade2f108ad0fd8a209df3a5cf76598/tensor2tensor/bin/t2t_trainer.py#L346

The code is passing None for all the arguments.

So hparams will be None in T2T experiment
https://github.com/tensorflow/tensor2tensor/blob/091373cd5eade2f108ad0fd8a209df3a5cf76598/tensor2tensor/utils/trainer_lib.py#L367

So the error about the attribute being None seems like its expected.

**Comment by cwbeitel** [comment]
It looks like create_experiment_fn obtains the hparams object from globals() instead of the function args.

```python
def create_experiment_fn(*args, **kwargs):
  """Wrapper for canonical experiment_fn. See create_experiment."""

  def experiment_fn(run_config, hparams):
    return create_experiment(run_config, hparams, *args, **kwargs)

  return experiment_fn
```
https://github.com/tensorflow/tensor2tensor/blob/091373cd5eade2f108ad0fd8a209df3a5cf76598/tensor2tensor/utils/trainer_lib.py#L695

based on the above and how it's called in t2t_trainer.main:

```python
  hparams = create_hparams()

  exp_fn = create_experiment_fn()
```
https://github.com/tensorflow/tensor2tensor/blob/091373cd5eade2f108ad0fd8a209df3a5cf76598/tensor2tensor/bin/t2t_trainer.py#L373

Looking at create_hparams it looks like the hparams object is originating from the hparams_set setting on FLAGS.

```python
def create_hparams():
  """Create hparams."""
  if FLAGS.use_tpu and "tpu" not in FLAGS.hparams_set:
    tf.logging.warn("Not all hyperparameter sets work on TPU. "
                    "Prefer hparams_sets with a '_tpu' suffix, "
                    "e.g. transformer_tpu, if available for your model.")
  hparams_path = os.path.join(FLAGS.output_dir, "hparams.json")
  return trainer_lib.create_hparams(FLAGS.hparams_set, FLAGS.hparams,
                                    hparams_path=hparams_path)

```

Given this I would first check whether FLAGS.hparams_set is set correctly such as by asserting the value of FLAGS.hparams_set before the return of create_hparams.

**Comment by jlewi** [comment]
I was able to work around this and get synchronous training working by

1. Creating my own python script to start a std server.
https://github.com/jlewi/examples/blob/cs_1103_train/code_search/src/code_search/t2t/start_std_server.py

1. Running this for the "workers"

1. Running this in a sidecar of the chief.

Here's the ksonnet comment
https://github.com/jlewi/examples/blob/cs_1103_train/code_search/kubeflow/components/demo-trainer-11-05-dist-sync-gpu.jsonnet

Here's the TFJob spec
[demo-trainer-11-07-dist-sync-gpu.yaml.txt](https://github.com/kubeflow/examples/files/2559988/demo-trainer-11-07-dist-sync-gpu.yaml.txt)

**Comment by colmantse** [comment]
as for now it seems this is still an unfixed issue. so we have to instantiate the server for master thread on our own i suppose?
